name = "workspace-script"
type = "triggered"
schema = 1

[workspace]
type = "script"
command = ["workspace-script-setup.sh"]

[trigger]
type = "manual"

[[steps]]
type = "shell"
command = ["git", "status"]
